### PR TITLE
WIP use of a fat jar (#11)

### PR DESCRIPTION
**Pull request by apupier**
- changed project to provide a fat jar but:
-- it used 0.7.0 as I wasn't able to find a wsdl2rest with all
dependencies available on provided repositories
-- folder where the jar is provided needs to be customized (currently
using the target one...)
-- the generation is not working because I think that parameters have
been changed between 0.7.0 and 0.8.0 and I didn't adapt them back
- it avoids to duplicate all dependencies
- it simplifies the command line to launch

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
on middle term, th ebest would be to have the fat jar genrated by wsdl2rest project and have a simple npm download artifact in the genrator project (it will avoid to have a mix of Maven and npm build system)

**Comment by bfitzpat** [comment]
@apupier - thanks for doing this. We were going at it in different ways. 

As for the wsdl2rest project doing that, I don't think it really would fall there. Could we spin off a separate wsdl2rest project that simply packages it as a fat jar and exposes it as a package through npm? Not sure how to do that exactly, but I bet we can figure it out...

**Comment by paoloantinori** [comment]
does this approach forces our project to take care of building the classpath correctly, or  is it no longer the case?

**Comment by apupier** [comment]
> does this approach forces our project to take care of building the classpath correctly, or is it no longer the case?

AFAIK springboot is taking care of the classpath

**Comment by apupier** [comment]
> As for the wsdl2rest project doing that, I don't think it really would fall there.

Why? If we have this requirement, I think it makes sense to have it in the wsdl2rest project itself.

> Could we spin off a separate wsdl2rest project that simply packages it as a fat jar 

that is also possible even if I think it will be easier to have it directly in wsdl2rest project

> and exposes it as a package through npm? Not sure how to do that exactly, but I bet we can figure it out...

for npm side of thing I don't know but I don't think that it is really necessary if we have the fat jar. We can download the artefact through npm-artefact-download as it is done in https://github.com/camel-tooling/camel-lsp-client-vscode/blob/master/scripts/preinstall.js , I think there won't anymore issues as it will be a single artefact.

**Comment by apupier** [comment]
approach now integrated in master of reference project

**Pull request closed without merging**
